# This file uses Maven placeholders that will be replaced during build
supabase.url=https://cwitbyqtrqcyhgmanfrm.supabase.co
supabase.key=sb_publishable_5ZwRa_BlQ8hR4LBQuGghBA_1htIJ-ZA

# Supabase PostgreSQL Connection - Using Session Pooler (IPv4 compatible)
# Format: jdbc:postgresql://[pooler-host]:[port]/postgres?user=[project-ref]&password=[password]&sslmode=require
db.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.cwitbyqtrqcyhgmanfrm&password=1qazZAQ!q1w2e3r4!


# Environment
env.name=development

# App settings
redis.url=rediss://default:AY_AAAIncDFlOWQ4Mzg4ODQ4MDQ0Yjc2YTdmMDEyZWJhYmM4NDA5OXAxMzY4MDA@massive-ocelot-36800.upstash.io:6379
